### ISSUE TITLE
MinimizeDataMovement does not work correctly for upsert tables

### ISSUE THREAD

**Issue by jadami10** [apache/pinot#11894]
We tried scaling up an upsert table and rebalancing. With MinimizeDataMovement, we still saw effectively every single segment moving to a different server. 

Upsert tables are more complicated because every segment for a partition has to live on the same server, so you typically need to scale up to some factor of your total partitions. But even then, the algorithm should strictly move partitions to new servers when scaling up. And in the case you do use a factor of total partitions, the end result should be some partitions are moved off of all existing servers to new servers.

**Comment by Jackie-Jiang** [comment]
@jackjlli Can you help take a look? I remember having some comments to be followed up in #8483, and this might be caused by that

**Comment by Jackie-Jiang** [comment]
Should be solved with #11953

**Comment by dang-stripe** [comment]
We've done some testing w/ upsert + `minimizeDataMovement` and it does not seem like this issue is fixed. We have a script to compare the ideal state w/ the output of the dry-run rebalance and still a significant number of segments being added to existing servers.

In this case, we have 2 pools with 4 servers and are adding 1 server to each pool.

With `minimizeDataMovement` off:
![Screenshot 2024-09-25 at 9 29 31 PM](https://github.com/user-attachments/assets/90aa688a-0089-4f1f-a18e-6f5409cda2ee)

With `minimizeDataMovement` on, there's barely any change:
![Screenshot 2024-09-25 at 9 29 36 PM](https://github.com/user-attachments/assets/3453ec6b-f499-4ce7-99bf-93cf48f24be7)

**Comment by dang-stripe** [comment]
We also tested the rebalance w/ low disk mode on a test table and still see data increase. Servers were at 37% and peaked at 52%.

![Screenshot 2024-09-26 at 9 34 31 AM](https://github.com/user-attachments/assets/458c1a62-5c17-4124-ad7f-38bca9417d25)

**Comment by Jackie-Jiang** [comment]
@dang-stripe Can you share the table config? If the partition - server mapping is not explicitly persisted, Pinot will round robin assigning partition to each server, and `minimizeDataMovement` might not take effect in that scenario

**Comment by dang-stripe** [comment]
we have 2 pools w/ 6 instances each and we added 1 instance per pool.

here's the instance assignment config:
```
    "instanceAssignmentConfigMap": {
      "CONSUMING": {
        "tagPoolConfig": {
          "tag": "test_REALTIME",
          "poolBased": true,
          "numPools": 2
        },
        "replicaGroupPartitionConfig": {
          "replicaGroupBased": true,
          "numInstances": 0,
          "numReplicaGroups": 2,
          "numInstancesPerReplicaGroup": 0,
          "numPartitions": 0,
          "numInstancesPerPartition": 0,
          "minimizeDataMovement": true
        },
        "partitionSelector": "INSTANCE_REPLICA_GROUP_PARTITION_SELECTOR",
        "minimizeDataMovement": true
      }
    },
```

here's the instance partition map from zk after rebalance:
```
{
  "id": "testtable_CONSUMING",
  "simpleFields": {},
  "mapFields": {},
  "listFields": {
    "0_0": [
      "testinstance-uswest2b-4_8098",
      "testinstance-uswest2b-5_8098",
      "testinstance-uswest2b-6_8098",
      "testinstance-uswest2b-1_8098",
      "testinstance-uswest2b-2_8098",
      "testinstance-uswest2b-3_8098",
      "testinstance-uswest2b-7_8098"
    ],
    "0_1": [
      "testinstance-uswest2a-4_8098",
      "testinstance-uswest2a-5_8098",
      "testinstance-uswest2a-6_8098",
      "testinstance-uswest2a-1_8098",
      "testinstance-uswest2a-2_8098",
      "testinstance-uswest2a-3_8098",
      "testinstance-uswest2a-7_8098"
    ]
  }
}
```
