### ISSUE TITLE
PERCENTILEEST throws NPE in MultiStage Engine

### ISSUE THREAD

**Issue by MeihanLi** [apache/pinot#13305]
we found in Pinot 1.1, PERCENTILEEST throws NPE in MultiStage Engine. Does anyone know if this is already fixed in master?

example query:
```
WITH sub AS (select deviceOS, count(1) as total_count from userAttributes group by 1 limit 100000),
subx AS (select deviceOS, count(1) as total_count from userAttributes group by 1 limit 100000),
union_table AS (select deviceOS, total_count from sub UNION ALL select deviceOS, total_count from subx)
select deviceOS, percentile(total_count, 50) from union_table group by deviceOS 
```

<img width="889" alt="image" src="https://github.com/apache/pinot/assets/42751784/c55cded4-80a7-4ab5-a60a-59544697cf4b">

**Comment by Jackie-Jiang** [comment]
Yes, it should be fixed within #13282

**Comment by ankitsultana** [comment]
Issue still exists. I am looking into it.

**Comment by ankitsultana** [comment]
@Jackie-Jiang : looks like current master still can't handle aggregations with literals in some cases. Repro is below.

I took a quick look and see the following issues:

* Calcite is converting RexLiteral to a ref
* [separate issue] We are generating an exchange for Percentile. Instead we should do a full aggregation directly.

I see a bunch of attempts at fixing this: 13282, 13217 and 11105.

I can take a look at this as well but wondering if you folks are already working on this and have any learnings to share.

```
SET useMultistageEngine=true;

with
  teamOne as (
  	select playerName, teamID, sum(runs) as sum_of_runs from baseballStats where teamID = 'SFN' group by playerName, teamID
  ),
  teamTwo as (
	select playerName, teamID, sum(runs) as sum_of_runs from baseballStats where teamID = 'CHN' group by playerName, teamID
  ),
  all as (
	select playerName, teamID, sum_of_runs from teamOne union all select playerName, teamID, sum_of_runs from teamTwo
  )
  select 
    teamID, 
	-- sum(sum_of_runs) 
	percentile(sum_of_runs, 50) 
  from all
  group by teamID
```

**Comment by Jackie-Jiang** [comment]
@ankitsultana Take a look at `PinotAggregateExchangeNodeInsertRule`, where we should already replace all ref to literal to literal. Maybe there are some corner cases not handled (e.g. the ref is not in a project)
