### ISSUE TITLE
Query with grouping columns but no aggregate ignores column aliases

### ISSUE THREAD

**Issue by elonazoulay** [apache/pinot#7546]
If a query has grouping columns but no aggregates the aliases are ignored.
To reproduce start the quick start batch and run the following query:
```
select AtBatting as foo, baseOnBalls as bar from baseballStats 
group by AtBatting, baseOnBalls
limit 10
```
Result uses `AtBatting` and `baseOnBalls` instead of `foo`, `bar`

If an aggregate is added then the aliases are correct:
```
select AtBatting as foo, baseOnBalls as bar , count(*) from baseballStats 
group by AtBatting, baseOnBalls
limit 10
```

**Comment by SandishKumarHN** [comment]
the issues is fixed as part of this PR https://github.com/apache/pinot/pull/7576/, just verified it.

**Comment by Jackie-Jiang** [comment]
@xiangfu0 @elonazoulay Can you please verify the fix and close the issue if the issue is fixed?

**Comment by kbastani** [comment]
I've just tested after compiling Pinot from master, and the issue still exists. 

```sql
SELECT CAST(calcs.int1 AS FLOAT) AS TEMP_Test__3817907367__0_
FROM calcs
GROUP BY 1
```

```json
{
  "resultTable": {
    "dataSchema": {
      "columnNames": [
        "cast(int1,'FLOAT')"
      ],
      "columnDataTypes": [
        "FLOAT"
      ]
    }, ...
 ```

**Comment by xiangfu0** [comment]
> I've just tested after compiling Pinot from master, and the issue still exists.
> 
> ```sql
> SELECT CAST(calcs.int1 AS FLOAT) AS TEMP_Test__3817907367__0_
> FROM calcs
> GROUP BY 1
> ```
> 
> ```json
> {
>   "resultTable": {
>     "dataSchema": {
>       "columnNames": [
>         "cast(int1,'FLOAT')"
>       ],
>       "columnDataTypes": [
>         "FLOAT"
>       ]
>     }, ...
> ```

The issue here is that in `NonAggregationGroupByToDistinctQueryRewriter.java`, Pinot rewrite this query
```SELECT CAST(calcs.int1 AS FLOAT) AS TEMP_Test__3817907367__0_
FROM calcs
GROUP BY 1
```
to
```SELECT DISTINCT calcs.int1
FROM calcs
```
And it loses the alias information.
@Jackie-Jiang

**Comment by kbastani** [comment]
@xiangfu0 @Jackie-Jiang Do we have an update on this fix?

**Comment by Jackie-Jiang** [comment]
Fixed by #7678
