### ISSUE TITLE
CAST used with GROUP BY causes weird exception

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#8424]
```
select 
  playerID, 
  cast(hits as long) AS totalHits
from baseballStats 
order by totalHits DESC
```
works fine.
```
select 
  playerID, 
  cast(count(hits) as long) AS totalHits
from baseballStats 
group by playerID
order by totalHits DESC
```
gives 
```
[
  {
    "message": "QueryExecutionError:\nProcessingException(errorCode:450, message:InternalError:\njava.lang.NullPointerException\n\tat org.apache.pinot.core.operator.combine.GroupByOrderByCombineOperator.mergeResults(GroupByOrderByCombineOperator.java:236)\n\tat org.apache.pinot.core.operator.combine.BaseCombineOperator.getNextBlock(BaseCombineOperator.java:119)\n\tat org.apache.pinot.core.operator.combine.BaseCombineOperator.getNextBlock(BaseCombineOperator.java:50)",
    "errorCode": 200
  }
]
```

**Comment by walterddr** [comment]
new finding is that 
```
select 
  playerID, 
  cast((hits - runs) as long) AS hitMinusRun
from baseballStats 
```
will work. thus the CAST functionKind exist, just no impl for this in scalarFunction probably. will take a look at the fix

**Comment by richardstartin** [comment]
> new finding is that
> 
> ```
> select 
>   playerID, 
>   cast((hits - runs) as long) AS hitMinusRun
> from baseballStats 
> ```
> 
> will work. thus the CAST functionKind exist, just no impl for this in scalarFunction probably. will take a look at the fix

It's fixed here @walterddr  #8535

**Comment by walterddr** [comment]
checked out the PR and tested. still doesn't work. let me poke around. thanks for the info @richardstartin

**Comment by richardstartin** [comment]
I doubt the cause is the absence of a scalar function then. The motivation of that PR is to ensure casts in filters don’t prevent index use.

**Comment by walterddr** [comment]
> I doubt the cause is the absence of a scalar function then. The motivation of that PR is to ensure casts in filters don’t prevent index use.

for the purpose of index use i think the PR works well. it doesn't solve what's describe in this issue though

**Comment by Jackie-Jiang** [comment]
Scalar function is used in the following places:
- Ingestion transform
- Compile time evaluation of literal only function
- Post aggregation transform
- If transform function is not implemented for the same name, scalar function can be used as transform function (poor performance)

For post aggregation transform and transform, if the result class for the scalar function is dynamic, we will treat it as `STRING`. In order to solve this problem, we need to add the support to derive the result type from the arguments' type.

**Comment by walterddr** [comment]
Initially I think we should wrap `@ScalarFunction` annotated methods into a `BuiltInScalarFunction implements FunctionDefinition` where all the interfaces are defined to support more complex function signatures. 

Similar architecture is adopted in many sql-like systems to support UDF/UDAF/UDTF etc. thus I think the design should be sufficient. I will create a separate design doc for the `FunctionDefinition` interface as well as how they will used for 
- dynamic arg/return type 
- stateful initialization (for example one of the arguments are literal expression)
- overloading and implicit type conversion if no exact arg type is found.
