### ISSUE TITLE
Pulsar test instability

### ISSUE THREAD

**Issue by walterddr** [apache/pinot#8537]
Error is occurring to Pulsar test case randomly on multiple of my PRs
```
PulsarConsumerTest.testPartitionLevelConsumerBatchMessages:246 expected [500] but found [491]
```

<details>
  <summary>CI Logs. Click to expand</summary>

  ```
  Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.324 s <<< FAILURE! - in org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest
  Error:  org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumer  Time elapsed: 0.845 s
  Error:  org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumerBatchMessages  Time elapsed: 0.48 s  <<< FAILURE!
  java.lang.AssertionError: expected [500] but found [491]
	  at org.testng.Assert.fail(Assert.java:93)
	  at org.testng.Assert.failNotEquals(Assert.java:512)
	  at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	  at org.testng.Assert.assertEquals(Assert.java:115)
	  at org.testng.Assert.assertEquals(Assert.java:388)
	  at org.testng.Assert.assertEquals(Assert.java:398)
	  at org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumerBatchMessages(PulsarConsumerTest.java:246)
	  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	  at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	  at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	  at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	  at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	  at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	  at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	  at org.testng.TestRunner.privateRun(TestRunner.java:744)
	  at org.testng.TestRunner.run(TestRunner.java:602)
	  at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	  at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	  at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	  at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	  at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	  at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	  at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	  at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	  at org.testng.TestNG.runSuites(TestNG.java:1144)
	  at org.testng.TestNG.run(TestNG.java:1115)
	  at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:136)
	  at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	  at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	  at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:145)
	  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	  at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	  at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
  
  [INFO] 
  [INFO] Results:
  [INFO] 
  Error:  Failures: 
  Error:    PulsarConsumerTest.testPartitionLevelConsumerBatchMessages:246 expected [500] but found [491]
  ```

</details>

**Comment by Jackie-Jiang** [comment]
Fixed by #8554

**Comment by KKcorps** [comment]
Re-opening the issue as it seems the flakiness is reduced but still occurs

**Comment by KKcorps** [comment]
OK. so the branch wasn't rebased in the PR :P

**Comment by walterddr** [comment]
this seems to be still recurring: https://github.com/apache/pinot/runs/6120269495?check_suite_focus=true. 

if I understood correctly github action always merge master before running tests. so PR base doesn't matter. see the log in the above test link
```
refs/remotes/pull/8580/merge
```

**Comment by Jackie-Jiang** [comment]
I'm still seeing the exact same failure. @KKcorps Please take another look

**Comment by Jackie-Jiang** [comment]
Another failure: https://github.com/apache/pinot/actions/runs/4366896907/jobs/7637509337

```
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 68.865 s <<< FAILURE! - in org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest
Error:  org.apache.pinot.plugin.stream.pulsar.PulsarConsumerTest.testPartitionLevelConsumer  Time elapsed: 0.507 s  <<< FAILURE!
java.lang.AssertionError: expected [500] but found [400]
```

**Comment by Jackie-Jiang** [comment]
Should be solved with #12812

**Comment by Jackie-Jiang** [comment]
Still flaky..

**Comment by Jackie-Jiang** [comment]
Closing this one and track it in #13008 which contains more details
